export const createStatements = [
    `create table AA (
    rollNumber char(19) not null,
    rollNumberCounty char(2) not null,
    rollNumberMunicipality char(2) not null,
    rollNumberMapArea char(2) not null,
    rollNumberMapDivision char(1) not null,
    rollNumberMapSubdivision char(3) not null,
    rollNumberParcel char(3) not null,
    rollNumberParcelSub char(2) not null,
    rollNumberPrimarySubordinate char(4) not null,
    ward char(2) not null,
    poll char(3) not null,
    pollSuffix char(1) not null,
    highSchoolCode char(2) not null,
    publicSchoolCode char(2) not null,
    separateSchoolCode char(2) not null,
    specialRateArea varchar(6) not null,
    pacCode char(3) not null,
    previousRollNumber char(19) not null,
    frenchPublicSchoolCode char(2) not null,
    frenchSeparateSchoolCode char(2) not null
  )`,
    `create table BB (
    rollNumber char(19) not null,
    frontage char(9) not null,
    frontageFeet double,
    frontageMetres double,
    siteArea char(10) not null,
    siteAreaSquareFeet double,
    siteAreaAcres double,
    unitOfMeasurement char(1) not null,
    depth char(8) not null,
    depthFeet double,
    depthMetres double,
    farmForestryExemptionAcres double,
    siteImprovement char(2) not null,
    siteImprovementHasBoathouse bit,
    siteImprovementHasSiteImprovements bit,
    siteImprovementHasOther bit,
    siteImprovementHasAccessibleFacilities bit,
    siteImprovementHasPool bit,
    siteImprovementHasElevator bit,
    siteImprovementHasSauna bit,
    siteImprovementHasMultiple bit,
    siteImprovementHasTennisCourts bit,
    propertyCode char(3) not null,
    propertyCodeClass varchar(20),
    propertyCodeName varchar(100),
    services char(1) not null,
    servicesName varchar(20),
    access char(1) not null,
    accessName varchar(40)
  )`,
    `create table CC (
    rollNumber char(19) not null,
    sequenceNumber char(1) not null,
    characterOfConstruction char(3) not null,
    characterOfConstructionDescription text,
    characterOfConstructionFramingDescription text,
    characterOfConstructionFloorDescription text,
    characterOfConstructionRoofDescription text,
    characterOfConstructionWallsDescription text,
    quality char(4) not null,
    shape char(1) not null,
    yearBuilt char(4) not null,
    yearBuiltCode char(1) not null,
    yearBuiltCodeName varchar(40),
    condition char(1) not null,
    conditionName varchar(10),
    conditionRakingOutOf5 tinyint,
    fullStoreys char(2) not null,
    partStoreys char(1) not null,
    partStoreysName varchar(20),
    heightEffectiveYearBuilt char(4) not null,
    heightFeet double,
    effectiveYearBuilt integer,
    split char(1) not null,
    splitName varchar(40),
    grossArea char(6) not null,
    grossAreaSquareFeet double,
    totalBasementArea char(4) not null,
    totalBasementAreaSquareFeet double,
    finishedBasementArea char(4) not null,
    finishedBasementAreaSquareFeet double,
    basementFinish char(1) not null,
    basementFinishName varchar(20),
    fullBaths char(1) not null,
    halfBaths char(1) not null,
    numberOfBedrooms char(2) not null,
    numberOfFireplaces char(1) not null,
    heatingType char(2) not null,
    heatingTypeName varchar(30),
    airConditioning char(1) not null,
    garageType char(1) not null,
    garageTypeName varchar(40),
    garageSpaces char(3) not null,
    structureCode char(3) not null,
    structureCodeClass varchar(20),
    structureCodeName varchar(100)
  )`
];
